"""update date things

Revision ID: 3801fe5de4c0
Revises: 44304383733f
Create Date: 2026-01-06 15:37:27.468746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3801fe5de4c0'
down_revision = '44304383733f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
