"""update date things

Revision ID: 45c7ff50eff2
Revises: 97ae912c84d5
Create Date: 2026-01-06 12:38:25.610510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45c7ff50eff2'
down_revision = '97ae912c84d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
