"""update column name

Revision ID: 97ae912c84d5
Revises: 50623fe5b5f7
Create Date: 2026-01-06 11:59:44.129914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97ae912c84d5'
down_revision = '50623fe5b5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination_reason', sa.String(length=50), nullable=True))
        batch_op.drop_column('termination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('termination_reason')

    # ### end Alembic commands ###
