"""added cascade

Revision ID: 9e2b718f5842
Revises: f3c0803b27ba
Create Date: 2026-01-20 06:39:35.027116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2b718f5842'
down_revision = 'f3c0803b27ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('game_moves_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('game_moves_ibfk_1'), 'game', ['game_id'], ['id'])

    # ### end Alembic commands ###
