"""added nullable

Revision ID: f3c0803b27ba
Revises: 3801fe5de4c0
Create Date: 2026-01-13 05:52:21.178182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c0803b27ba'
down_revision = '3801fe5de4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('san',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_moves', schema=None) as batch_op:
        batch_op.alter_column('san',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)

    # ### end Alembic commands ###
